modLoader="kotlinforforge"
loaderVersion="[5.3,)"
license="${mod_license}"

[[mods]]
modId="bulkit"
version="${mod_version}"
displayName="BulkIt"
authors="${mod_authors}"
description=''''''

[[dependencies.bulkit]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.bulkit]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"