modLoader="kotlinforforge"
loaderVersion="[5.3,)"
license="${mod_license}"

[[mods]]
modId="bulkit_mekanism"
version="0.1.0-alpha"
displayName="BulkIt (Mekanism)"
authors="${mod_authors}"
description=''''''

[[dependencies.bulkit_mekanism]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.bulkit_mekanism]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.bulkit_mekanism]]
modId="bulkit"
type="required"
versionRange="[0.1,)"
ordering="AFTER"
side="BOTH"